sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - clang
    - fakeroot
    - g++-4.8
    - git
    - libgnome-keyring-dev
    - xvfb
    - rpm
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev
branches:
  only:
  - master
  - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/
matrix:
  include:
  - os: linux
    env: NODE_VERSION=6.9 CC=gcc-4.8 CXX=g++-4.8 DEBUG="electron-packager:*" INSTALL_TARGET=client
  - os: osx
    env: NODE_VERSION=6.9 CC=clang CXX=clang++ SIGN_BUILD=true DEBUG="electron-packager:*"
      INSTALL_TARGET=client
before_install:
- if [ ${TRAVIS_PULL_REQUEST} = "false" ]; then openssl aes-256-cbc -K $encrypted_1670798fb6bd_key
  -iv $encrypted_1670798fb6bd_iv -in ~/build/nylas-mail-lives/nylas-mail/certs/nml.p12.enc
  -out ~/build/nylas-mail-lives/nylas-mail/certs/nml.p12 -d; fi
install:
- git clone https://github.com/creationix/nvm.git /tmp/.nvm
- source /tmp/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use --delete-prefix $NODE_VERSION
before_script:
- if [ ${TRAVIS_OS_NAME} = "osx" ] && [ ${TRAVIS_PULL_REQUEST} = "false" ]; then security
  delete-keychain nml-build.keychain; security create-keychain -p travis nml-build.keychain;
  security default-keychain -s nml-build.keychain; security unlock-keychain -p travis
  nml-build.keychain; security import ~/build/nylas-mail-lives/nylas-mail/certs/AppleWWDRCA.cer
  -k ~/Library/Keychains/nml-build.keychain -T /usr/bin/codesign; security import
  ~/build/nylas-mail-lives/nylas-mail/certs/nml.cer -k ~/Library/Keychains/nml-build.keychain
  -T /usr/bin/codesign; security import ~/build/nylas-mail-lives/nylas-mail/certs/nml.p12
  -k ~/Library/Keychains/nml-build.keychain -P $NML_CERTIFICATE_PASSWORD -T /usr/bin/codesign;
  else SIGN_BUILD=false; fi
script:
- npm install && npm run build-client
cache:
  directories:
  - node_modules
  - apm/node_modules
deploy:
  provider: releases
  api_key:
    secure: KxWuAdzcOkWq8z1/7/OapOYDD95/kMKQs9jvuvC+JEH8qz1JdZXJ2es8UfHU8YCu5bmD31xyLf0MXMSHa2JKKM0C0+TRYrkfickbuQt3L5hfAZWObJRS0u29RsHKv+vX1unwDUuPXEdjCx6DAfNMCKtHf86HBXcOXczVkPP8c9IUFUp+34LzOahOprkIyKUVRid9K3JgtftuVHNHMLnQQKwrnEsehYq+2PJIsAi1HwhJ5fHU4qHXBYrAeT1/nF91upv+K1WFvYxvipOqYS1PeX6FsIOwvhjOZ6BXgn60keD3LoiTejvX0T/7W7fK1E9L6L/20QuHnsHQrPL9xZWbSiV+Jkrd3USUVrWnD2vo83juDA1tVekp4KvHWzA76g43ndOgMcDfJrkRh5+gi/2kfhMBrM1FKK89KdxUGSCY9mz+al1JtuqdHWZm0VU2h1GO9PYiL3qlWlljEIX0jciDnm7icLWODN+jP7MXTD8JNvAVVw8VMneao6LtXTZQ3HUVGnbpenvk+1Y/qZZK4Qtw/kB8Wug8LVDXcI3Qx57RJCut6QweM65uowwkUatFSFZ8vl/XOizGR0EQpTVo/ZYpi0QWEh8pg6hFfF8Gn/1UbC5SEZbm0o4V07xliqDzBhHKkQbX3dll/EYTiPVxT8epjcfKest74y2f7awSHjOo+cw=
  file-glob: true
  file:
    - "/home/travis/build/nylas-mail-lives/nylas-mail/packages/client-app/dist/*.deb"
    - "/home/travis/build/nylas-mail-lives/nylas-mail/packages/client-app/dist/*.rpm"
    - "/home/travis/build/nylas-mail-lives/nylas-mail/packages/client-app/dist/*.dmg"
  skip_cleanup: true
  on:
    tags: true
